# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-07 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ansible_Playbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playbook_name', models.CharField(max_length=50, unique=True, verbose_name='\u5267\u672c\u540d\u79f0')),
                ('playbook_desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u529f\u80fd\u63cf\u8ff0')),
                ('playbook_vars', models.TextField(blank=True, null=True, verbose_name='\u6a21\u5757\u53c2\u6570')),
                ('playbook_uuid', models.CharField(max_length=50, verbose_name='\u552f\u4e00id')),
                ('playbook_file', models.FileField(upload_to='./upload/playbook/', verbose_name='\u5267\u672c\u8def\u5f84')),
                ('playbook_auth_group', models.SmallIntegerField(blank=True, null=True, verbose_name='\u6388\u6743\u7ec4')),
                ('playbook_auth_user', models.SmallIntegerField(blank=True, null=True, verbose_name='\u6388\u6743\u7528\u6237')),
            ],
            options={
                'db_table': 'opsmanage_ansible_playbook',
                'verbose_name': 'Ansible\u5267\u672c\u914d\u7f6e\u8868',
                'verbose_name_plural': 'Ansible\u5267\u672c\u914d\u7f6e\u8868',
                'permissions': (('can_read_ansible_playbook', '\u8bfb\u53d6Ansible\u5267\u672c\u6743\u9650'), ('can_change_ansible_playbook', '\u66f4\u6539Ansible\u5267\u672c\u6743\u9650'), ('can_add_ansible_playbook', '\u6dfb\u52a0Ansible\u5267\u672c\u6743\u9650'), ('can_delete_ansible_playbook', '\u5220\u9664Ansible\u5267\u672c\u6743\u9650')),
            },
        ),
        migrations.CreateModel(
            name='Ansible_Playbook_Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playbook_server', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u76ee\u6807\u670d\u52a1\u5668')),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_number', to='devsapp.Ansible_Playbook')),
            ],
            options={
                'db_table': 'opsmanage_ansible_playbook_number',
                'verbose_name': 'Ansible\u5267\u672c\u6210\u5458\u8868',
                'verbose_name_plural': 'Ansible\u5267\u672c\u6210\u5458\u8868',
                'permissions': (('can_read_ansible_playbook_number', '\u8bfb\u53d6Ansible\u5267\u672c\u6210\u5458\u6743\u9650'), ('can_change_ansible_playbook_number', '\u66f4\u6539Ansible\u5267\u672c\u6210\u5458\u6743\u9650'), ('can_add_ansible_playbook_number', '\u6dfb\u52a0Ansible\u5267\u672c\u6210\u5458\u6743\u9650'), ('can_delete_ansible_playbook_number', '\u5220\u9664Ansible\u5267\u672c\u6210\u5458\u6743\u9650')),
            },
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=32)),
                ('hostname', models.CharField(max_length=32)),
                ('cpu_number', models.IntegerField(blank=True, default=1, null=True)),
                ('kernel', models.CharField(blank=True, max_length=64)),
                ('model', models.CharField(blank=True, max_length=32)),
                ('system', models.CharField(blank=True, max_length=64)),
                ('vcpu_number', models.IntegerField(blank=True, default=1, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('disk_total', models.CharField(blank=True, max_length=12)),
                ('cpu_core', models.IntegerField(blank=True, default=2, null=True)),
                ('swap', models.CharField(blank=True, max_length=12)),
                ('ram_total', models.CharField(blank=True, max_length=12)),
                ('selinux', models.CharField(blank=True, max_length=12)),
                ('serial', models.CharField(blank=True, max_length=32)),
                ('cpu', models.CharField(blank=True, max_length=64)),
                ('manufacturer', models.CharField(blank=True, max_length=32)),
                ('buiness', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_caption', models.CharField(max_length=64, verbose_name='\u8bbe\u5907\u540d\u79f0')),
                ('device_serial', models.CharField(max_length=64, verbose_name='\u8bbe\u5907\u5e8f\u5217\u53f7')),
                ('device_vendor', models.CharField(choices=[('huawei', 'huawei'), ('cisco', 'cisco'), ('lenovo', 'lenovo')], default='huawei', max_length=32, verbose_name='\u8bbe\u5907\u5382\u5546')),
                ('device_type', models.CharField(max_length=32, verbose_name='\u8bbe\u5907\u7c7b\u578b')),
                ('device_remarks', models.CharField(max_length=255, verbose_name='\u5907\u6ce8')),
                ('device_ip', models.GenericIPAddressField(verbose_name='\u8bbe\u5907ip')),
                ('device_status', models.CharField(max_length=32, verbose_name='\u8bbe\u5907\u72b6\u6001')),
                ('device_signer', models.CharField(max_length=32, verbose_name='\u767b\u8bb0\u4eba')),
                ('device_signtime', models.DateTimeField(auto_now_add=True)),
                ('device_user', models.CharField(max_length=32, verbose_name='\u8bbe\u5907\u7528\u6237\u540d')),
                ('device_password', models.CharField(max_length=32, verbose_name='\u8bbe\u5907\u5bc6\u7801')),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_code', models.CharField(max_length=32, verbose_name='\u7ebf\u8def\u7f16\u53f7')),
                ('line_local', models.CharField(default='\u5317\u4eac', max_length=64, verbose_name='\u6240\u5728\u533a\u57df')),
                ('line_speed', models.CharField(choices=[('2M', '2M'), ('4M', '4M'), ('8M', '8M')], default='6M', max_length=32, verbose_name='\u7ebf\u8def\u901f\u7387')),
                ('line_spname', models.CharField(choices=[('\u8054\u901a', '\u8054\u901a'), ('\u7535\u4fe1', '\u7535\u4fe1'), ('\u79fb\u52a8', '\u79fb\u52a8')], max_length=32, verbose_name='\u8fd0\u8425\u5546')),
                ('line_type', models.CharField(choices=[('MSTP', 'MSTP'), ('MSDP', 'MSDP')], max_length=32, verbose_name='\u7ebf\u8def\u7c7b\u578b')),
                ('line_status', models.BooleanField(default=True, verbose_name='\u7ebf\u8def\u542f\u7528')),
                ('line_open', models.DateField(verbose_name='\u5f00\u901a\u65f6\u95f4')),
                ('line_close', models.DateField(blank=True, null=True, verbose_name='\u5173\u95ed\u65f6\u95f4')),
                ('line_signer', models.CharField(max_length=32, verbose_name='\u7ebf\u8def\u767b\u8bb0\u4eba')),
                ('line_signtime', models.DateTimeField(auto_now_add=True)),
                ('line_remarks', models.CharField(blank=True, max_length=255, verbose_name='\u7ebf\u8def\u5907\u6ce8')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=32, verbose_name='\u673a\u623f\u540d\u5b57')),
                ('node_type', models.CharField(choices=[('\u5317\u4eac', '\u5317\u4eac'), ('\u5176\u4ed6', '\u5176\u4ed6')], max_length=32, verbose_name='\u673a\u623f\u7c7b\u578b')),
                ('node_address', models.CharField(max_length=62, verbose_name='\u673a\u623f\u5730\u5740')),
                ('node_contanct', models.CharField(max_length=32, verbose_name='\u673a\u623f\u8054\u7cfb\u4eba')),
                ('node_signer', models.CharField(max_length=32, verbose_name='\u673a\u623f\u767b\u8bb0\u4eba')),
                ('node_remarks', models.CharField(max_length=64, verbose_name='\u5907\u6ce8')),
                ('node_signtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('name', models.CharField(default='noName', max_length=100, primary_key=True, serialize=False)),
                ('info', models.CharField(default='noUse', max_length=100)),
                ('script', models.TextField(default='')),
                ('status', models.IntegerField(choices=[(0, '\u672a\u5b8c\u6210'), (1, '\u5df2\u5b8c\u6210')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ScriptArgs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('args_name', models.CharField(default='', max_length=100)),
                ('args_value', models.CharField(default='', max_length=100)),
                ('script', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scriptargs', to='devsapp.Script')),
            ],
        ),
        migrations.CreateModel(
            name='Server_Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('hostname', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('passwd', models.CharField(blank=True, max_length=100, null=True)),
                ('keyfile', models.SmallIntegerField(blank=True, null=True)),
                ('port', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('line', models.CharField(blank=True, max_length=100, null=True)),
                ('cpu', models.CharField(blank=True, max_length=100, null=True)),
                ('cpu_number', models.SmallIntegerField(blank=True, null=True)),
                ('vcpu_number', models.SmallIntegerField(blank=True, null=True)),
                ('cpu_core', models.SmallIntegerField(blank=True, null=True)),
                ('disk_total', models.CharField(blank=True, max_length=100, null=True)),
                ('ram_total', models.CharField(blank=True, max_length=100, null=True)),
                ('kernel', models.CharField(blank=True, max_length=100, null=True)),
                ('selinux', models.CharField(blank=True, max_length=100, null=True)),
                ('swap', models.CharField(blank=True, max_length=100, null=True)),
                ('raid', models.SmallIntegerField(blank=True, null=True)),
                ('system', models.CharField(blank=True, max_length=100, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('assets', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='devsapp.Assets')),
            ],
            options={
                'db_table': 'opsmanage_server_assets',
                'verbose_name': '\u670d\u52a1\u5668\u8d44\u4ea7\u8868',
                'verbose_name_plural': '\u670d\u52a1\u5668\u8d44\u4ea7\u8868',
                'permissions': (('can_read_server_assets', '\u8bfb\u53d6\u670d\u52a1\u5668\u8d44\u4ea7\u6743\u9650'), ('can_change_server_assets', '\u66f4\u6539\u670d\u52a1\u5668\u8d44\u4ea7\u6743\u9650'), ('can_add_server_assets', '\u6dfb\u52a0\u670d\u52a1\u5668\u8d44\u4ea7\u6743\u9650'), ('can_delete_server_assets', '\u5220\u9664\u670d\u52a1\u5668\u8d44\u4ea7\u6743\u9650')),
            },
        ),
        migrations.CreateModel(
            name='service_assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100, unique=None)),
            ],
        ),
        migrations.CreateModel(
            name='SSHInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=100)),
                ('port', models.IntegerField(default=22)),
                ('usr', models.CharField(max_length=50)),
                ('pwd', models.CharField(max_length=100)),
                ('ssh_key', models.TextField()),
                ('state', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='line',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devsapp.Node'),
        ),
        migrations.AddField(
            model_name='device',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devsapp.Node'),
        ),
    ]
