# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-23 04:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_caption', models.CharField(max_length=64, verbose_name='\u8bbe\u5907\u540d\u79f0')),
                ('device_serial', models.CharField(max_length=64, verbose_name='\u8bbe\u5907\u5e8f\u5217\u53f7')),
                ('device_vendor', models.CharField(choices=[('huawei', 'huawei'), ('cisco', 'cisco'), ('lenovo', 'lenovo')], default='huawei', max_length=32, verbose_name='\u8bbe\u5907\u5382\u5546')),
                ('device_type', models.CharField(max_length=32, verbose_name='\u8bbe\u5907\u7c7b\u578b')),
                ('device_remarks', models.CharField(max_length=255, verbose_name='\u5907\u6ce8')),
                ('device_ip', models.GenericIPAddressField(verbose_name='\u8bbe\u5907ip')),
                ('device_status', models.CharField(max_length=32, verbose_name='\u8bbe\u5907\u72b6\u6001')),
                ('device_signer', models.CharField(max_length=32, verbose_name='\u767b\u8bb0\u4eba')),
                ('device_signtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_code', models.CharField(max_length=32, verbose_name='\u7ebf\u8def\u7f16\u53f7')),
                ('line_local', models.CharField(default='\u5317\u4eac', max_length=64, verbose_name='\u6240\u5728\u533a\u57df')),
                ('line_speed', models.CharField(choices=[('2M', '2M'), ('4M', '4M'), ('8M', '8M')], default='6M', max_length=32, verbose_name='\u7ebf\u8def\u901f\u7387')),
                ('line_spname', models.CharField(choices=[('\u8054\u901a', '\u8054\u901a'), ('\u7535\u4fe1', '\u7535\u4fe1'), ('\u8054\u901a', '\u8054\u901a')], max_length=32, verbose_name='\u8fd0\u8425\u5546')),
                ('line_type', models.CharField(choices=[('MSTP', 'MSTP'), ('MSDP', 'MSDP')], max_length=32, verbose_name='\u7ebf\u8def\u7c7b\u578b')),
                ('line_status', models.BooleanField(default=True, verbose_name='\u7ebf\u8def\u542f\u7528')),
                ('line_open', models.DateField(verbose_name='\u5f00\u901a\u65f6\u95f4')),
                ('line_close', models.DateField(blank=True, null=True, verbose_name='\u5173\u95ed\u65f6\u95f4')),
                ('line_signer', models.CharField(max_length=32, verbose_name='\u7ebf\u8def\u767b\u8bb0\u4eba')),
                ('line_signtime', models.DateTimeField(auto_now_add=True)),
                ('line_remarks', models.CharField(blank=True, max_length=255, verbose_name='\u7ebf\u8def\u5907\u6ce8')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=32, verbose_name='\u8282\u70b9\u540d\u5b57')),
                ('node_type', models.CharField(choices=[('\u5317\u4eac', '\u5317\u4eac'), ('\u5176\u4ed6', '\u5176\u4ed6')], max_length=32, verbose_name='\u8282\u70b9\u7c7b\u578b')),
                ('node_address', models.CharField(max_length=62, verbose_name='\u8282\u70b9\u5730\u5740')),
                ('node_contanct', models.CharField(max_length=32, verbose_name='\u8282\u70b9\u8054\u7cfb\u4eba')),
                ('node_signer', models.CharField(max_length=32, verbose_name='\u8282\u70b9\u767b\u8bb0\u4eba')),
                ('node_remarks', models.CharField(max_length=64, verbose_name='\u5907\u6ce8')),
                ('node_signtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='line',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devsapp.Node'),
        ),
        migrations.AddField(
            model_name='device',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devsapp.Node'),
        ),
    ]
