# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-24 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('devsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_password',
            field=models.CharField(default=django.utils.timezone.now, max_length=32, verbose_name='\u8bbe\u5907\u5bc6\u7801'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='device_user',
            field=models.CharField(default=django.utils.timezone.now, max_length=32, verbose_name='\u8bbe\u5907\u7528\u6237\u540d'),
            preserve_default=False,
        ),
    ]
