# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-07 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('devsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='id',
            field=models.AutoField(primary_key=True),
            preserve_default=False,
        ),
    ]
