# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-25 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devsapp', '0002_auto_20170824_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSHInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=100)),
                ('port', models.IntegerField(default=22)),
                ('usr', models.CharField(max_length=50)),
                ('pwd', models.CharField(max_length=100)),
                ('state', models.IntegerField(default=0)),
            ],
        ),
    ]
