# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-09 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devsapp', '0003_toolsscript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sshinfo',
            name='ssh_key',
            field=models.TextField(null=True),
        ),
    ]
