# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devsapp', '0003_sshinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=32)),
                ('hostname', models.CharField(max_length=32)),
                ('cpu_number', models.IntegerField()),
                ('kernel', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=32)),
                ('system', models.CharField(max_length=64)),
                ('vcpu_number', models.IntegerField()),
                ('status', models.IntegerField()),
                ('disk_total', models.CharField(max_length=12)),
                ('cpu_core', models.IntegerField()),
                ('swap', models.CharField(max_length=12)),
                ('ram_total', models.CharField(max_length=12)),
                ('selinux', models.CharField(max_length=12)),
                ('serial', models.CharField(max_length=32)),
                ('cpu', models.CharField(max_length=64)),
                ('manufacturer', models.CharField(max_length=32)),
            ],
        ),
    ]
