# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-07-03 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devsapp', '0005_auto_20180409_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskScripts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=100)),
                ('tasksteps', models.CharField(max_length=1000)),
            ],
        ),
    ]
