# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-07-04 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devsapp', '0006_taskscripts'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskscripts',
            name='describe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
