# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2020-12-27 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devsapp', '0007_taskscripts_describe'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemid', models.CharField(max_length=64)),
                ('clock', models.DateTimeField(auto_now=True)),
                ('uint', models.CharField(max_length=10)),
                ('value', models.CharField(max_length=10)),
                ('endpoint', models.CharField(max_length=32)),
                ('mpoint', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='History_str',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemid', models.CharField(max_length=64)),
                ('clock', models.DateTimeField(auto_now=True)),
                ('uint', models.CharField(max_length=10)),
                ('value', models.CharField(max_length=10)),
                ('endpoint', models.CharField(max_length=32)),
                ('mpoint', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='History_text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemid', models.CharField(max_length=64)),
                ('clock', models.DateTimeField(auto_now=True)),
                ('uint', models.TextField()),
                ('value', models.CharField(max_length=10)),
                ('endpoint', models.CharField(max_length=32)),
                ('mpoint', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='History_uint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemid', models.CharField(max_length=64)),
                ('clock', models.DateTimeField(auto_now=True)),
                ('uint', models.IntegerField()),
                ('value', models.CharField(max_length=10)),
                ('endpoint', models.CharField(max_length=32)),
                ('mpoint', models.CharField(max_length=32)),
            ],
        ),
    ]
