# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2021-04-15 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devsapp', '0009_auto_20201227_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='History_metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemid', models.CharField(max_length=64)),
                ('endpoint', models.CharField(max_length=32)),
            ],
        ),
    ]
