# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2021-04-18 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devsapp', '0010_history_metric'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemid', models.CharField(max_length=32)),
                ('hostid', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('value_type', models.CharField(max_length=16)),
                ('t_create', models.DateTimeField(auto_now=True)),
                ('t_modify', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='history',
            name='itemid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devsapp.Items'),
        ),
        migrations.AlterField(
            model_name='history_str',
            name='itemid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devsapp.Items'),
        ),
        migrations.AlterField(
            model_name='history_text',
            name='itemid',
            field=models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, to='devsapp.Items'),
        ),
        migrations.AlterField(
            model_name='history_uint',
            name='itemid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devsapp.Items'),
        ),
    ]
