# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2021-04-18 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devsapp', '0011_auto_20210418_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostid', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=12)),
                ('hostname', models.CharField(max_length=32)),
                ('t_create', models.DateTimeField(auto_now=True)),
                ('t_modify', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='items',
            name='hostid',
            field=models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.CASCADE, to='devsapp.hosts'),
        ),
    ]
